// <auto-generated />
using System;
using DTB.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DTB.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240320150436_AddedNewTableContactFormSubmission")]
    partial class AddedNewTableContactFormSubmission
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CompanyLocation", b =>
                {
                    b.Property<string>("CompaniesId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LocationsId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CompaniesId", "LocationsId");

                    b.HasIndex("LocationsId");

                    b.ToTable("CompanyLocation");
                });

            modelBuilder.Entity("DTB.Infrastructure.Data.Entities.Article", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AuthorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfCreation")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("DTB.Infrastructure.Data.Entities.BaseUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ChatId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfilePicture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("BaseUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("DTB.Infrastructure.Data.Entities.Category", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateOfCreation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PictureUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = "51e3a8a0-c40e-4429-8658-1e10d71a18cb",
                            DateOfCreation = new DateTime(2024, 3, 20, 17, 4, 36, 346, DateTimeKind.Local).AddTicks(6894),
                            Name = "Architecture, Construction",
                            PictureUrl = "https://res.cloudinary.com/dftfu5p0r/image/upload/v1709824820/icon_architecture_gqdlbl.png"
                        },
                        new
                        {
                            Id = "ee94ba4c-ae17-47c3-a908-5fa54dcac53a",
                            DateOfCreation = new DateTime(2024, 3, 20, 17, 4, 36, 346, DateTimeKind.Local).AddTicks(6936),
                            Name = "Health and Pharmacy",
                            PictureUrl = "https://res.cloudinary.com/dftfu5p0r/image/upload/v1709824820/icon_health_nhktmm.png"
                        },
                        new
                        {
                            Id = "10e507b7-0677-411c-9afe-068164dd2d1c",
                            DateOfCreation = new DateTime(2024, 3, 20, 17, 4, 36, 346, DateTimeKind.Local).AddTicks(6952),
                            Name = "Drivers, Couriers",
                            PictureUrl = "https://res.cloudinary.com/dftfu5p0r/image/upload/v1709824821/icon_derivers_q8g7p3.png"
                        },
                        new
                        {
                            Id = "91bc1661-6b3d-4de9-b8ee-51be729e87ef",
                            DateOfCreation = new DateTime(2024, 3, 20, 17, 4, 36, 346, DateTimeKind.Local).AddTicks(6959),
                            Name = "Restaurants, Bars, Hotels, Tourism",
                            PictureUrl = "https://res.cloudinary.com/dftfu5p0r/image/upload/v1709824823/icon_restaurant_ee4ubg.png"
                        },
                        new
                        {
                            Id = "44506664-a42d-4a20-8c52-cd4e029b3be5",
                            DateOfCreation = new DateTime(2024, 3, 20, 17, 4, 36, 346, DateTimeKind.Local).AddTicks(6966),
                            Name = "Engineers and Technicians",
                            PictureUrl = "https://res.cloudinary.com/dftfu5p0r/image/upload/v1709824820/icon_engineer_wzjia1.png"
                        },
                        new
                        {
                            Id = "3788e599-5e1b-410a-9020-a60b27484eb2",
                            DateOfCreation = new DateTime(2024, 3, 20, 17, 4, 36, 346, DateTimeKind.Local).AddTicks(6976),
                            Name = "Human Resources",
                            PictureUrl = "https://res.cloudinary.com/dftfu5p0r/image/upload/v1709824820/icon_hr_jbc5jn.png"
                        },
                        new
                        {
                            Id = "109ec738-74b2-4dd7-bd9c-4f496e43f3c5",
                            DateOfCreation = new DateTime(2024, 3, 20, 17, 4, 36, 346, DateTimeKind.Local).AddTicks(6983),
                            Name = "Media, Publishing",
                            PictureUrl = "https://res.cloudinary.com/dftfu5p0r/image/upload/v1709824821/icon_media_mpzkez.png"
                        },
                        new
                        {
                            Id = "c85eaa5f-a5c0-4a73-b219-207bee6d848f",
                            DateOfCreation = new DateTime(2024, 3, 20, 17, 4, 36, 346, DateTimeKind.Local).AddTicks(6989),
                            Name = "Logistics, Spedition",
                            PictureUrl = "https://res.cloudinary.com/dftfu5p0r/image/upload/v1709824821/icon_logistic_ktvoqa.png"
                        },
                        new
                        {
                            Id = "b1e639ef-3fb9-4022-abfb-20d5a49d93f0",
                            DateOfCreation = new DateTime(2024, 3, 20, 17, 4, 36, 346, DateTimeKind.Local).AddTicks(6996),
                            Name = "Customer support",
                            PictureUrl = "https://res.cloudinary.com/dftfu5p0r/image/upload/v1709824820/icon_customersupport_fbvie5.png"
                        },
                        new
                        {
                            Id = "49d281b5-b10c-4780-be7a-ac920b03c4df",
                            DateOfCreation = new DateTime(2024, 3, 20, 17, 4, 36, 346, DateTimeKind.Local).AddTicks(7004),
                            Name = "Banking, Lending, Insurance",
                            PictureUrl = "https://res.cloudinary.com/dftfu5p0r/image/upload/v1709824820/icon_banking_dkgjma.png"
                        },
                        new
                        {
                            Id = "059bb67a-c45c-49e7-9a2f-eb33b2020bb7",
                            DateOfCreation = new DateTime(2024, 3, 20, 17, 4, 36, 346, DateTimeKind.Local).AddTicks(7011),
                            Name = "Marketing, Advertising, PR",
                            PictureUrl = "https://res.cloudinary.com/dftfu5p0r/image/upload/v1709824820/icon_hr_jbc5jn.png"
                        },
                        new
                        {
                            Id = "c1d31fb9-9857-45a1-b1b4-66dc00ccf12f",
                            DateOfCreation = new DateTime(2024, 3, 20, 17, 4, 36, 346, DateTimeKind.Local).AddTicks(7018),
                            Name = "Office and Business activities",
                            PictureUrl = "https://res.cloudinary.com/dftfu5p0r/image/upload/v1709824821/icon_office_xkdjih.png"
                        },
                        new
                        {
                            Id = "10af519f-189e-4681-b195-0235a09aaf8e",
                            DateOfCreation = new DateTime(2024, 3, 20, 17, 4, 36, 346, DateTimeKind.Local).AddTicks(7025),
                            Name = "Energy, Water and Sewage, Utilities",
                            PictureUrl = "https://res.cloudinary.com/dftfu5p0r/image/upload/v1709824820/icon_energy_kznsrc.png"
                        },
                        new
                        {
                            Id = "2f96d59b-255b-41af-9b70-6ed0399d84cb",
                            DateOfCreation = new DateTime(2024, 3, 20, 17, 4, 36, 346, DateTimeKind.Local).AddTicks(7031),
                            Name = "Telecommunications - engineers and technicians",
                            PictureUrl = "https://res.cloudinary.com/dftfu5p0r/image/upload/v1709824825/icon_telecoms_sbsq5u.png"
                        },
                        new
                        {
                            Id = "a9b974a9-c287-4f74-ad43-1345f04c67fc",
                            DateOfCreation = new DateTime(2024, 3, 20, 17, 4, 36, 346, DateTimeKind.Local).AddTicks(7038),
                            Name = "Education, Courses, Translators",
                            PictureUrl = "https://res.cloudinary.com/dftfu5p0r/image/upload/v1709824821/icon_education_kdsm7z.png"
                        },
                        new
                        {
                            Id = "dd980b0a-6fa4-470d-8311-8f5e601b8c51",
                            DateOfCreation = new DateTime(2024, 3, 20, 17, 4, 36, 346, DateTimeKind.Local).AddTicks(7044),
                            Name = "Security",
                            PictureUrl = "https://res.cloudinary.com/dftfu5p0r/image/upload/v1709824825/icon_security_c4fjq0.png"
                        },
                        new
                        {
                            Id = "972cd369-4840-42bd-be94-c7f25183a9b8",
                            DateOfCreation = new DateTime(2024, 3, 20, 17, 4, 36, 346, DateTimeKind.Local).AddTicks(7051),
                            Name = "Real-estate",
                            PictureUrl = "https://res.cloudinary.com/dftfu5p0r/image/upload/v1709824821/icon_realestate_dkhhfe.png"
                        },
                        new
                        {
                            Id = "f613c771-90af-4acf-8da5-dfe686be98a4",
                            DateOfCreation = new DateTime(2024, 3, 20, 17, 4, 36, 346, DateTimeKind.Local).AddTicks(7058),
                            Name = "Legal",
                            PictureUrl = "https://res.cloudinary.com/dftfu5p0r/image/upload/v1709824821/icon_legal_ofzofx.png"
                        },
                        new
                        {
                            Id = "9136c27f-24f5-42e7-b4a3-9c737d6eefd3",
                            DateOfCreation = new DateTime(2024, 3, 20, 17, 4, 36, 346, DateTimeKind.Local).AddTicks(7065),
                            Name = "Aviation, Airport & Airline",
                            PictureUrl = "https://res.cloudinary.com/dftfu5p0r/image/upload/v1709824820/icon_airline_bgvmiu.png"
                        },
                        new
                        {
                            Id = "f253c296-de78-4da9-841e-55a39ccc70ea",
                            DateOfCreation = new DateTime(2024, 3, 20, 17, 4, 36, 346, DateTimeKind.Local).AddTicks(7071),
                            Name = "Auto Service",
                            PictureUrl = "https://res.cloudinary.com/dftfu5p0r/image/upload/v1709824819/icon_autoservice_iabxkj.png"
                        },
                        new
                        {
                            Id = "7012c3a2-b566-4be7-bb5c-005919969fe1",
                            DateOfCreation = new DateTime(2024, 3, 20, 17, 4, 36, 346, DateTimeKind.Local).AddTicks(7078),
                            Name = "Retail, Wholesale",
                            PictureUrl = "https://res.cloudinary.com/dftfu5p0r/image/upload/v1709824824/icon_retail_pgicm9.png"
                        },
                        new
                        {
                            Id = "5dcbb653-d6bb-4ab7-8623-55461c729553",
                            DateOfCreation = new DateTime(2024, 3, 20, 17, 4, 36, 346, DateTimeKind.Local).AddTicks(7084),
                            Name = "Technical Support",
                            PictureUrl = "https://res.cloudinary.com/dftfu5p0r/image/upload/v1709824825/icon_techsupport_zph0mx.png"
                        },
                        new
                        {
                            Id = "d303b80e-871f-4aab-b6ef-5b419cd2bd24",
                            DateOfCreation = new DateTime(2024, 3, 20, 17, 4, 36, 346, DateTimeKind.Local).AddTicks(7090),
                            Name = "Research and development",
                            PictureUrl = "https://res.cloudinary.com/dftfu5p0r/image/upload/v1709824822/icon_research_mdrafi.png"
                        },
                        new
                        {
                            Id = "4b76d573-9dd4-4f0d-b347-ecb8a988a607",
                            DateOfCreation = new DateTime(2024, 3, 20, 17, 4, 36, 346, DateTimeKind.Local).AddTicks(7097),
                            Name = "Accouting, Audit, Finance",
                            PictureUrl = "https://res.cloudinary.com/dftfu5p0r/image/upload/v1709824820/icon_finance_r5bftt.png"
                        });
                });

            modelBuilder.Entity("DTB.Infrastructure.Data.Entities.Chat", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("DTB.Infrastructure.Data.Entities.Comment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ArticleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AuthorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("AuthorId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("DTB.Infrastructure.Data.Entities.ContactFormSubmission", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ContactFormSubmissions");
                });

            modelBuilder.Entity("DTB.Infrastructure.Data.Entities.File", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("DTB.Infrastructure.Data.Entities.JobAd", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CompanyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Experience")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LocationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProfessionId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("LocationId");

                    b.HasIndex("ProfessionId");

                    b.ToTable("JobAds");
                });

            modelBuilder.Entity("DTB.Infrastructure.Data.Entities.Location", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = "332312f1-b597-4e8a-877a-c10da74ba24d",
                            Name = "Sofia"
                        },
                        new
                        {
                            Id = "58d4ddbc-ddce-4652-9bd1-4c9c34a6d043",
                            Name = "Burgas"
                        },
                        new
                        {
                            Id = "67d9b96a-f3ec-4eae-93e6-b9fc79924d46",
                            Name = "Plovdiv"
                        },
                        new
                        {
                            Id = "16842a20-7069-4cbd-a2bd-ff67ef1a6009",
                            Name = "Varna"
                        },
                        new
                        {
                            Id = "8044c37e-2030-4ca7-9a7a-5f0978c02d62",
                            Name = "Yambol"
                        },
                        new
                        {
                            Id = "3a6eb306-e99f-431f-b382-68b5e0893bf4",
                            Name = "Blagoevgrad"
                        },
                        new
                        {
                            Id = "80eb2aad-8f49-4157-b803-13db4d4067de",
                            Name = "Sliven"
                        },
                        new
                        {
                            Id = "d499deb5-cbc8-429e-9ddd-c465b07a0bfd",
                            Name = "Dimitrovgrad"
                        },
                        new
                        {
                            Id = "f2a9357d-67ba-4ddd-904f-fbeef44b1fb1",
                            Name = "Ruse"
                        },
                        new
                        {
                            Id = "83687b12-0d45-4746-942f-42135419c6e1",
                            Name = "Elhovo"
                        });
                });

            modelBuilder.Entity("DTB.Infrastructure.Data.Entities.Message", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ChatId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiverId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SenderId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("DTB.Infrastructure.Data.Entities.Profession", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Professions");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DTB.Infrastructure.Data.Entities.Company", b =>
                {
                    b.HasBaseType("DTB.Infrastructure.Data.Entities.BaseUser");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasIndex("CategoryId");

                    b.HasDiscriminator().HasValue("Company");
                });

            modelBuilder.Entity("DTB.Infrastructure.Data.Entities.User", b =>
                {
                    b.HasBaseType("DTB.Infrastructure.Data.Entities.BaseUser");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("JobAdId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProfessionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasIndex("JobAdId");

                    b.HasIndex("ProfessionId");

                    b.HasDiscriminator().HasValue("User");
                });

            modelBuilder.Entity("CompanyLocation", b =>
                {
                    b.HasOne("DTB.Infrastructure.Data.Entities.Company", null)
                        .WithMany()
                        .HasForeignKey("CompaniesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DTB.Infrastructure.Data.Entities.Location", null)
                        .WithMany()
                        .HasForeignKey("LocationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DTB.Infrastructure.Data.Entities.Article", b =>
                {
                    b.HasOne("DTB.Infrastructure.Data.Entities.BaseUser", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("DTB.Infrastructure.Data.Entities.BaseUser", b =>
                {
                    b.HasOne("DTB.Infrastructure.Data.Entities.Chat", null)
                        .WithMany("Participants")
                        .HasForeignKey("ChatId");
                });

            modelBuilder.Entity("DTB.Infrastructure.Data.Entities.Comment", b =>
                {
                    b.HasOne("DTB.Infrastructure.Data.Entities.Article", "Article")
                        .WithMany("Comments")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DTB.Infrastructure.Data.Entities.BaseUser", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId");

                    b.Navigation("Article");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("DTB.Infrastructure.Data.Entities.File", b =>
                {
                    b.HasOne("DTB.Infrastructure.Data.Entities.User", null)
                        .WithMany("Files")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("DTB.Infrastructure.Data.Entities.JobAd", b =>
                {
                    b.HasOne("DTB.Infrastructure.Data.Entities.Category", "Category")
                        .WithMany("JobAds")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DTB.Infrastructure.Data.Entities.Company", "Company")
                        .WithMany("JobAds")
                        .HasForeignKey("CompanyId");

                    b.HasOne("DTB.Infrastructure.Data.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId");

                    b.HasOne("DTB.Infrastructure.Data.Entities.Profession", "Profession")
                        .WithMany()
                        .HasForeignKey("ProfessionId");

                    b.Navigation("Category");

                    b.Navigation("Company");

                    b.Navigation("Location");

                    b.Navigation("Profession");
                });

            modelBuilder.Entity("DTB.Infrastructure.Data.Entities.Message", b =>
                {
                    b.HasOne("DTB.Infrastructure.Data.Entities.Chat", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DTB.Infrastructure.Data.Entities.BaseUser", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId");

                    b.HasOne("DTB.Infrastructure.Data.Entities.BaseUser", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId");

                    b.Navigation("Chat");

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("DTB.Infrastructure.Data.Entities.Profession", b =>
                {
                    b.HasOne("DTB.Infrastructure.Data.Entities.Category", "Category")
                        .WithMany("Professions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DTB.Infrastructure.Data.Entities.BaseUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DTB.Infrastructure.Data.Entities.BaseUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DTB.Infrastructure.Data.Entities.BaseUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DTB.Infrastructure.Data.Entities.BaseUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DTB.Infrastructure.Data.Entities.Company", b =>
                {
                    b.HasOne("DTB.Infrastructure.Data.Entities.Category", "Category")
                        .WithMany("Companies")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DTB.Infrastructure.Data.Entities.User", b =>
                {
                    b.HasOne("DTB.Infrastructure.Data.Entities.JobAd", null)
                        .WithMany("Candidates")
                        .HasForeignKey("JobAdId");

                    b.HasOne("DTB.Infrastructure.Data.Entities.Profession", "Profession")
                        .WithMany()
                        .HasForeignKey("ProfessionId");

                    b.Navigation("Profession");
                });

            modelBuilder.Entity("DTB.Infrastructure.Data.Entities.Article", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("DTB.Infrastructure.Data.Entities.Category", b =>
                {
                    b.Navigation("Companies");

                    b.Navigation("JobAds");

                    b.Navigation("Professions");
                });

            modelBuilder.Entity("DTB.Infrastructure.Data.Entities.Chat", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("DTB.Infrastructure.Data.Entities.JobAd", b =>
                {
                    b.Navigation("Candidates");
                });

            modelBuilder.Entity("DTB.Infrastructure.Data.Entities.Company", b =>
                {
                    b.Navigation("JobAds");
                });

            modelBuilder.Entity("DTB.Infrastructure.Data.Entities.User", b =>
                {
                    b.Navigation("Files");
                });
#pragma warning restore 612, 618
        }
    }
}
